<p style="font-family: Arial; font-size:3.75em;color:purple; font-style:bold"><br>
Introduction to numpy:
</p><br>

<p style="font-family: Arial; font-size:1.25em;color:#2462C0; font-style:bold"><br>
Package for scientific computing with Python
</p><br>

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.  Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.  

The key features of numpy are:

- ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient.  There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).
- Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.
- Vectorization: enables numeric operations on ndarrays.
- Input/Output: simplifies reading and writing of data from/to file.

<b>Additional Recommended Resources:</b><br>
<a href="https://docs.scipy.org/doc/numpy/reference/">Numpy Documentation</a><br>
<i>Python for Data Analysis</i> by Wes McKinney<br>
<i>Python Data science Handbook</i> by Jake VanderPlas



<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Getting Started with ndarray</p>

**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy. Like the data structures in Python.


<p style="font-family: Arial; font-size:1.75em;color:#2324A0; font-style:bold"><br>
How to create Rank 1 Numpy arrays</p>

In [1]:
import numpy as np
an_array = np.array([3,33,333])  #Create a rank array

print(type(an_array))

<type 'numpy.ndarray'>


In [2]:
# test the shape of the array we just created, it should have just one dimension

an_array.shape

(3,)

In [3]:
# bcoz this is a 1-rank array, we need only one index to access each elememt
print(an_array[0], an_array[1], an_array[2])

(3, 33, 333)


In [4]:
# nd.arrays are mutable but strongly typed
an_array[1] = 122
print(an_array)

[  3 122 333]


<p style="font-family:Arial; font-size:1.35em; color:#1234CC; font-style:bold;"><br>


How to create a Rank 2 numpy array</p>

In [5]:
another = np.array([[11,22,13],[21,22,33]])
print(another)

[[11 22 13]
 [21 22 33]]


In [6]:
print(another.shape) # 2 Rows and 3 columns

(2, 3)


In [7]:
print("Access Elements", another[0,1])

('Access Elements', 22)


<p style="font-family:Arial; color:#1234CC; font-size:1.35em; font-style:bold">

There are a number of ways to create numpy arrays</p>
<p>Here we create a number of different size arrays with **different shapes** and **different pre-filled values**. numpy has a number of built in methods which help us quickly and easily create **multidimensional arrays**</p>

In [11]:
import numpy as np

np.zeros((2,3)) # Create 2 x 3 arrays of zeroes

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
# Create a 2x3 arrays filled with 10
np.full((2,3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [14]:
# Create a diagnol matrix
np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [21]:
ex1 = np.ones((1))
print (ex1)
ex = np.ones((1,2))
print (ex)
print(ex.shape) # Its a 2 dimension array


[ 1.]
[[ 1.  1.]]
(1, 2)


In [23]:
np.random.random((2,4))

array([[ 0.26289711,  0.2527843 ,  0.41692068,  0.76928835],
       [ 0.98018936,  0.6920459 ,  0.32189034,  0.55647146]])